/// A crop recommendation generated by the recommendation engine.
///
/// Uses a Multi-Dimensional Crop Recommendation Score Model (5 factors)
/// and a Predictive Risk Model (4 factors) for thesis-grade analysis.
class CropRecommendation {
  final String id;
  final String farmerId;
  final String recommendedCrop;
  final List<String> companionCrops;
  final double suitabilityScore; // 0-100 composite score
  final String season;
  final double waterAvailability;
  final String saturationLevel;
  final double estimatedRevenue;
  final double estimatedCost;
  final double estimatedProfit;
  final String riskLevel; // 'low', 'medium', 'high'
  final double regionalSaturation;
  final String reason;
  final bool isIntercrop;
  final DateTime? expectedHarvest;
  final DateTime createdAt;

  // ── Multi-Dimensional Score Breakdown (each 0.0 – 1.0) ──
  final double profitScore;       // Weight: 0.35
  final double climateScore;      // Weight: 0.20
  final double marketRiskScore;   // Weight: 0.20
  final double soilScore;         // Weight: 0.15
  final double diversificationScore; // Weight: 0.10

  // ── Predictive Risk Breakdown (each 0.0 – 1.0) ──
  final double weatherRisk;       // Weight: 0.30
  final double marketRisk;        // Weight: 0.30
  final double cropSensitivity;   // Weight: 0.20
  final double financialRisk;     // Weight: 0.20
  final double totalRiskScore;    // 0.0 – 1.0 probability

  CropRecommendation({
    required this.id,
    required this.farmerId,
    required this.recommendedCrop,
    required this.companionCrops,
    required this.suitabilityScore,
    required this.season,
    required this.waterAvailability,
    required this.saturationLevel,
    required this.estimatedRevenue,
    required this.estimatedCost,
    required this.estimatedProfit,
    required this.riskLevel,
    required this.regionalSaturation,
    required this.reason,
    required this.isIntercrop,
    this.expectedHarvest,
    this.profitScore = 0.0,
    this.climateScore = 0.0,
    this.marketRiskScore = 0.0,
    this.soilScore = 0.0,
    this.diversificationScore = 0.0,
    this.weatherRisk = 0.0,
    this.marketRisk = 0.0,
    this.cropSensitivity = 0.0,
    this.financialRisk = 0.0,
    this.totalRiskScore = 0.0,
    DateTime? createdAt,
  }) : createdAt = createdAt ?? DateTime.now();

  factory CropRecommendation.fromJson(Map<String, dynamic> json) {
    return CropRecommendation(
      id: json['id'] ?? '',
      farmerId: json['farmer_id'] ?? '',
      recommendedCrop: json['recommended_crop'] ?? '',
      companionCrops: json['companion_crops'] is List
          ? List<String>.from(json['companion_crops'])
          : [],
      suitabilityScore: (json['suitability_score'] is num)
          ? (json['suitability_score'] as num).toDouble()
          : 0.0,
      season: json['season'] ?? '',
      waterAvailability: (json['soil_moisture'] is num)
          ? (json['soil_moisture'] as num).toDouble()
          : 0.0,
      saturationLevel: json['saturation_level'] ?? 'medium',
      estimatedRevenue: (json['estimated_revenue'] is num)
          ? (json['estimated_revenue'] as num).toDouble()
          : 0.0,
      estimatedCost: (json['estimated_cost'] is num)
          ? (json['estimated_cost'] as num).toDouble()
          : 0.0,
      estimatedProfit: (json['estimated_profit'] is num)
          ? (json['estimated_profit'] as num).toDouble()
          : 0.0,
      riskLevel: json['risk_level'] ?? 'medium',
      regionalSaturation: (json['regional_saturation'] is num)
          ? (json['regional_saturation'] as num).toDouble()
          : 0.0,
      reason: json['reason'] ?? '',
      isIntercrop: json['is_intercrop'] ?? false,
      expectedHarvest: json['expected_harvest'] is String
          ? DateTime.parse(json['expected_harvest'])
          : null,
      profitScore: (json['profit_score'] is num)
          ? (json['profit_score'] as num).toDouble()
          : 0.0,
      climateScore: (json['climate_score'] is num)
          ? (json['climate_score'] as num).toDouble()
          : 0.0,
      marketRiskScore: (json['market_risk_score'] is num)
          ? (json['market_risk_score'] as num).toDouble()
          : 0.0,
      soilScore: (json['soil_score'] is num)
          ? (json['soil_score'] as num).toDouble()
          : 0.0,
      diversificationScore: (json['diversification_score'] is num)
          ? (json['diversification_score'] as num).toDouble()
          : 0.0,
      weatherRisk: (json['weather_risk'] is num)
          ? (json['weather_risk'] as num).toDouble()
          : 0.0,
      marketRisk: (json['market_risk'] is num)
          ? (json['market_risk'] as num).toDouble()
          : 0.0,
      cropSensitivity: (json['crop_sensitivity'] is num)
          ? (json['crop_sensitivity'] as num).toDouble()
          : 0.0,
      financialRisk: (json['financial_risk'] is num)
          ? (json['financial_risk'] as num).toDouble()
          : 0.0,
      totalRiskScore: (json['total_risk_score'] is num)
          ? (json['total_risk_score'] as num).toDouble()
          : 0.0,
      createdAt: json['created_at'] is String
          ? DateTime.parse(json['created_at'])
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'farmer_id': farmerId,
      'recommended_crop': recommendedCrop,
      'companion_crops': companionCrops,
      'suitability_score': suitabilityScore,
      'season': season,
      'soil_moisture': waterAvailability,
      'saturation_level': saturationLevel,
      'estimated_revenue': estimatedRevenue,
      'estimated_cost': estimatedCost,
      'estimated_profit': estimatedProfit,
      'risk_level': riskLevel,
      'regional_saturation': regionalSaturation,
      'reason': reason,
      'is_intercrop': isIntercrop,
      'expected_harvest': expectedHarvest?.toIso8601String().split('T').first,
      'profit_score': profitScore,
      'climate_score': climateScore,
      'market_risk_score': marketRiskScore,
      'soil_score': soilScore,
      'diversification_score': diversificationScore,
      'weather_risk': weatherRisk,
      'market_risk': marketRisk,
      'crop_sensitivity': cropSensitivity,
      'financial_risk': financialRisk,
      'total_risk_score': totalRiskScore,
    };
  }

  /// Risk level emoji.
  String get riskEmoji {
    switch (riskLevel) {
      case 'low':
        return '🟢';
      case 'medium':
        return '🟡';
      case 'high':
        return '🔴';
      default:
        return '⚪';
    }
  }

  /// Formatted suitability percent.
  String get suitabilityPercent => '${suitabilityScore.toStringAsFixed(0)}%';
}

/// Supply projection for harvest synchronization.
class SupplyProjection {
  final String id;
  final String cropType;
  final double projectedYieldKg;
  final DateTime harvestWindowStart;
  final DateTime harvestWindowEnd;
  final int farmerCount;
  final double totalAreaHa;
  final double riskOfOversupply;
  final String suggestedAction;
  final String region;

  SupplyProjection({
    required this.id,
    required this.cropType,
    required this.projectedYieldKg,
    required this.harvestWindowStart,
    required this.harvestWindowEnd,
    required this.farmerCount,
    required this.totalAreaHa,
    required this.riskOfOversupply,
    required this.suggestedAction,
    required this.region,
  });

  factory SupplyProjection.fromJson(Map<String, dynamic> json) {
    return SupplyProjection(
      id: json['id'] ?? '',
      cropType: json['crop_type'] ?? '',
      projectedYieldKg: (json['projected_yield_kg'] is num)
          ? (json['projected_yield_kg'] as num).toDouble()
          : 0.0,
      harvestWindowStart: json['harvest_window_start'] is String
          ? DateTime.parse(json['harvest_window_start'])
          : DateTime.now(),
      harvestWindowEnd: json['harvest_window_end'] is String
          ? DateTime.parse(json['harvest_window_end'])
          : DateTime.now(),
      farmerCount: (json['farmer_count'] is num)
          ? (json['farmer_count'] as num).toInt()
          : 0,
      totalAreaHa: (json['total_area_ha'] is num)
          ? (json['total_area_ha'] as num).toDouble()
          : 0.0,
      riskOfOversupply: (json['risk_of_oversupply'] is num)
          ? (json['risk_of_oversupply'] as num).toDouble()
          : 0.0,
      suggestedAction: json['suggested_action'] ?? '',
      region: json['region'] ?? 'local',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'crop_type': cropType,
      'projected_yield_kg': projectedYieldKg,
      'harvest_window_start':
          harvestWindowStart.toIso8601String().split('T').first,
      'harvest_window_end':
          harvestWindowEnd.toIso8601String().split('T').first,
      'farmer_count': farmerCount,
      'total_area_ha': totalAreaHa,
      'risk_of_oversupply': riskOfOversupply,
      'suggested_action': suggestedAction,
      'region': region,
    };
  }

  String get oversupplyRiskLabel {
    if (riskOfOversupply >= 75) return 'CRITICAL';
    if (riskOfOversupply >= 50) return 'HIGH';
    if (riskOfOversupply >= 25) return 'MODERATE';
    return 'LOW';
  }

  String get projectedYieldTons =>
      (projectedYieldKg / 1000).toStringAsFixed(1);
}

/// Subsidy allocation tracking for calamity reports.
class SubsidyAllocation {
  final String id;
  final String calamityReportId;
  final String farmerId;
  final String? verifiedBy;
  final DateTime? verificationDate;
  final double subsidyAmount;
  final String status; // 'pending','verified','approved','disbursed','rejected'
  final String? verificationNotes;
  final DateTime createdAt;

  SubsidyAllocation({
    required this.id,
    required this.calamityReportId,
    required this.farmerId,
    this.verifiedBy,
    this.verificationDate,
    required this.subsidyAmount,
    required this.status,
    this.verificationNotes,
    DateTime? createdAt,
  }) : createdAt = createdAt ?? DateTime.now();

  factory SubsidyAllocation.fromJson(Map<String, dynamic> json) {
    return SubsidyAllocation(
      id: json['id'] ?? '',
      calamityReportId: json['calamity_report_id'] ?? '',
      farmerId: json['farmer_id'] ?? '',
      verifiedBy: json['verified_by'],
      verificationDate: json['verification_date'] is String
          ? DateTime.parse(json['verification_date'])
          : null,
      subsidyAmount: (json['subsidy_amount'] is num)
          ? (json['subsidy_amount'] as num).toDouble()
          : 0.0,
      status: json['status'] ?? 'pending',
      verificationNotes: json['verification_notes'],
      createdAt: json['created_at'] is String
          ? DateTime.parse(json['created_at'])
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'calamity_report_id': calamityReportId,
      'farmer_id': farmerId,
      'verified_by': verifiedBy,
      'verification_date':
          verificationDate?.toIso8601String().split('T').first,
      'subsidy_amount': subsidyAmount,
      'status': status,
      'verification_notes': verificationNotes,
    };
  }

  String get statusEmoji {
    switch (status) {
      case 'pending':
        return '⏳';
      case 'verified':
        return '✅';
      case 'approved':
        return '👍';
      case 'disbursed':
        return '💰';
      case 'rejected':
        return '❌';
      default:
        return '⚪';
    }
  }

  String get statusLabel {
    switch (status) {
      case 'pending':
        return 'Pending Review';
      case 'verified':
        return 'Verified';
      case 'approved':
        return 'Approved';
      case 'disbursed':
        return 'Disbursed';
      case 'rejected':
        return 'Rejected';
      default:
        return status;
    }
  }
}
